apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    field.cattle.io/publicEndpoints: '[{"addresses":["35.223.119.84"],"port":80,"protocol":"TCP","serviceName":"default:survey-server","allNodes":false}]'
  creationTimestamp: "2021-03-11T23:53:42Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: survey-server
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-expose
    operation: Update
    time: '2021-03-27T03:09:38Z'
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"service.kubernetes.io/load-balancer-cleanup": {}
      f:status:
        f:loadBalancer:
          f:ingress: {}
    manager: kube-controller-manager
    operation: Update
    time: '2021-03-27T03:10:12Z'
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:field.cattle.io/publicEndpoints: {}
    manager: rancher
    operation: Update
    time: '2021-03-27T03:10:12Z' 
  name: survey-server
  namespace: default
  resourceVersion: '8809175'
  selfLink: /api/v1/namespaces/default/services/survey-server
  uid: 0d2b4cf6-0519-47b8-bd44-0f2331e2502f
spec:
  clusterIP: 10.16.5.158
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32696
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: survey-server
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.223.119.84
