apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: survey-server
  name: survey-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: survey-server
  template:
    metadata:
      labels:
        app: survey-server
    spec:
      containers:
      - image: risshie/swe642:2021-03-21-18-58-08
        name: survey-server
